import time

print("CURSO EM VIDEO - PYTHON: TABUADA\n")
time.sleep(3)
alvo = int(input("Digite um número para ver sua tabuada\n"))
time.sleep(3)
print("____________TABUADA____________")
print(alvo,"* 0 = ",alvo*0)
print(alvo,"* 1 = ",alvo*1)
print(alvo,"* 2 = ",alvo*2)
print(alvo,"* 3 = ",alvo*3)
print(alvo,"* 4 = ",alvo*4)
print(alvo,"* 5 = ",alvo*5)
print(alvo,"* 6 = ",alvo*6)
print(alvo,"* 7 = ",alvo*7)
print(alvo,"* 8 = ",alvo*8)
print(alvo,"* 9 = ",alvo*9)
print(alvo,"* 10 = ",alvo*10)
print("_______________________________")
time.sleep(30)
